### ISSUE TITLE
Lag server

### ISSUE THREAD

**Issue by xPiston** [libraryaddict/LibsDisguises#364]
Hello, with your last commit it's totally unplayable mobs disgust tp in all directions, it does not move any more

**Comment by greasemonkey123** [comment]
Can you please write this in a _readable_ form of English?

**Comment by xPiston** [comment]
Since the last days since the disguise mobs are totally bugged (he is tp in wave, he is motionless)

**Comment by libraryaddict** [comment]
Please confirm the issue is fixed

**Comment by xPiston** [comment]
I have no more lag but I still have the crash minecraft #336

**Comment by greasemonkey123** [comment]
Can you send the console logs?
