### ISSUE TITLE
NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment

### ISSUE THREAD

**Issue by ofunny** [libraryaddict/LibsDisguises#706]
After updating to the latest Paper build 511 for 1.19.4 (https://papermc.io/downloads/paper) even the latest dev build of LibsDisguises v10.0.32-SNAPSHOT throws the following exception on startup. 

https://mcpaste.io/ceff2b9c168c6267

**Comment by libraryaddict** [comment]
Should be fixed in latest builds, including some support for older versions of paper/spigot to work

**Comment by GabrielTK** [comment]
Still happening to me on Jenkins #[1181](https://ci.md-5.net/job/LibsDisguises/1181/)

**Comment by libraryaddict** [comment]
Latest builds of spigot and paper sorry, seems like my fix for outdated builds doesn't apply
